# Generated by Django 4.1.1 on 2022-10-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('direction_destinations', models.JSONField()),
                ('direction_names', models.JSONField()),
                ('line', models.CharField(max_length=255)),
                ('polylines', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.JSONField()),
                ('municipality', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('line', models.JSONField()),
                ('location', models.JSONField()),
                ('status', models.CharField(max_length=255, null=True)),
                ('stop', models.JSONField(null=True)),
                ('occupancy', models.CharField(max_length=255, null=True)),
                ('speed', models.FloatField(null=True)),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
