# Generated by Django 4.1.1 on 2022-10-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('line', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('bearing', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('stop', models.CharField(max_length=255)),
            ],
        ),
    ]
