# Generated by Django 4.1.1 on 2022-11-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='direction_id',
            field=models.IntegerField(null=True),
        ),
    ]
