# Generated by Django 4.1.1 on 2022-10-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='stop',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
