# Generated by Django 4.1.1 on 2022-10-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit_api', '0003_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='bearing',
        ),
        migrations.RemoveField(
            model_name='train',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='train',
            name='longitude',
        ),
        migrations.AddField(
            model_name='train',
            name='location',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='transit_api.location'),
            preserve_default=False,
        ),
    ]
