# Generated by Django 4.1.1 on 2022-10-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit_api', '0005_alter_train_location_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.JSONField()),
                ('municipality', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='train',
            name='line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transit_api.line'),
        ),
        migrations.AlterField(
            model_name='train',
            name='stop',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='transit_api.stop'),
            preserve_default=False,
        ),
    ]
