# Generated by Django 4.1.1 on 2022-10-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_api', '0007_alter_stop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
