# Generated by Django 4.1.1 on 2022-10-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_api', '0008_alter_stop_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='color',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
