# Generated by Django 4.1.1 on 2022-10-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_api', '0009_line_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='lines',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
