# Generated by Django 4.1.1 on 2022-10-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_api', '0010_stop_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='direction_destinations',
            field=models.JSONField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='direction_names',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='line',
            field=models.CharField(default={'hi': 1}, max_length=255),
            preserve_default=False,
        ),
    ]
