# Generated by Django 4.1.1 on 2022-10-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_api', '0011_line_direction_destinations_line_direction_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='polylines',
            field=models.JSONField(default='1:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='occupancy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='line',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='stop',
            field=models.JSONField(null=True),
        ),
    ]
