# Generated by Django 4.1.1 on 2022-10-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_api', '0012_line_polylines_train_occupancy_train_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='last_update',
            field=models.DateTimeField(default='2013-06-23'),
            preserve_default=False,
        ),
    ]
