# Generated by Django 4.1.1 on 2022-10-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit_api', '0015_stop_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='lines',
        ),
    ]
